//
// Created by is021433 on 12/14/2023.
//

#ifndef GRAPH_PUZZLE_GAME_ILAYDASURKULTAY_HEAPNODE_H
#define GRAPH_PUZZLE_GAME_ILAYDASURKULTAY_HEAPNODE_H


class HeapNode {

};


#endif //GRAPH_PUZZLE_GAME_ILAYDASURKULTAY_HEAPNODE_H
